### ISSUE TITLE
Support JOIN

### ISSUE THREAD

**Issue by mytototo** [BatchLabs/charlatan#2]
Hi,

Thanks for this project. I was looking for a SQL-like interpreter to learn how it works and I found it really useful. 

Do you have plans / ideas how to support JOIN across records?

**Comment by bfontaine** [comment]
I don’t think it’s feasible given that `charlatan` works on stream-like data and a `JOIN` operator requires indexed (or at least sorted) fields.

**Comment by mytototo** [comment]
So, given those two JSON, a JOIN is impossible even if we pass the two JSON files as records?

`people.json`
```js
{"name": "Nico", "age": 54, "stats": {"walking": 42, "running": 104, "biking": 13}, "country_id": 2}
{"name": "Vincent", "age": 32, "stats": {"walking": 100, "running": 2, "biking": 3}, "country_id": 1}
{"name": "Cedric", "age": 52, "stats": {"walking": 2, "running": 2, "biking": 1000}, "country_id": 3}
{"name": "Michel", "age": 83, "stats": {"walking": 0, "running": 0, "biking": 0}, "country_id": 2}
{"name": "Gerard", "age": 55, "stats": {"walking": 54, "running": 12, "biking": 33}, "country_id": 4}
```

`countries.json`
```js
{"id": 1, "code": "USA"}
{"id": 2, "code": "UK"}
{"id": 3, "code": "Spain"}
{"id": 4, "code": "France"}
```

**Comment by bfontaine** [comment]
Well, it’s _possible_, but not with the current API. Unless you want to try each pair of records you’d need some kind of indexing and random access, which is equivalent to re-implementing a database system. It would be a good exercise, but it goes far beyond the scope of `charlatan`.

**Comment by mytototo** [comment]
Ok I understand. Thanks for your help @bfontaine.
